import { getNextSpellingWord, submitSpellingAttempt, completeSpellingChallenge } from './spelling.js';

export class SpellingChallengeController {
  constructor({ overlay, onComplete }) {
    this.overlay = overlay; this.title = overlay.querySelector('[data-wormhole-title]'); this.phaseLabel = overlay.querySelector('[data-wormhole-phase]'); this.wordDisplay = overlay.querySelector('[data-wormhole-word]'); this.input = overlay.querySelector('[data-wormhole-input]'); this.feedback = overlay.querySelector('[data-wormhole-feedback]'); this.readyButton = overlay.querySelector('[data-wormhole-ready]'); this.testButton = overlay.querySelector('[data-wormhole-test]'); this.checkButton = overlay.querySelector('[data-wormhole-check]'); this.onComplete = onComplete; this.challenges = new Map(); this.queue = []; this.activePlayerId = null;
    this.readyButton.addEventListener('click', () => this.beginPractice()); this.testButton.addEventListener('click', () => this.beginRetrieval()); this.input.addEventListener('input', () => this.checkPractice()); this.checkButton.addEventListener('click', () => this.submitRetrieval()); overlay.querySelector('[data-wormhole-form]').addEventListener('submit', (event) => { event.preventDefault(); this.submitRetrieval(); });
  }
  begin({ playerId, reason }) { if (this.challenges.has(playerId)) return; const wordRecord = getNextSpellingWord({ playerId, studentId: null }); const challenge = { playerId, reason, ...wordRecord, phase: 'learn', retrievalAttempts: 0, startedAt: Date.now(), completedAt: null }; this.challenges.set(playerId, challenge); this.queue.push(playerId); this.showNext(); }
  showNext() { if (this.activePlayerId || !this.queue.length) return; this.activePlayerId = this.queue.shift(); const challenge = this.challenges.get(this.activePlayerId); this.overlay.classList.add('visible'); this.overlay.setAttribute('aria-hidden', 'false'); this.input.value = ''; this.feedback.textContent = ''; this.render(challenge); }
  render(challenge) { const learning = challenge.phase === 'learn'; const practice = challenge.phase === 'practice'; const retrieval = challenge.phase === 'retrieval'; this.title.textContent = `PLAYER ${challenge.playerId}`; this.phaseLabel.textContent = learning ? 'YOUR WORD IS' : practice ? 'PRACTICE - COPY THE WORD' : 'SPELL THE WORD FROM MEMORY'; this.wordDisplay.textContent = learning || practice ? challenge.word.toUpperCase() : ''; this.wordDisplay.classList.toggle('hidden-word', retrieval); this.input.disabled = learning || challenge.phase === 'complete'; this.input.setAttribute('aria-hidden', learning ? 'true' : 'false'); this.readyButton.hidden = !learning; this.testButton.hidden = !practice; this.checkButton.hidden = !retrieval; this.testButton.disabled = practice && this.input.value.trim().toLowerCase() !== challenge.word.toLowerCase(); if (practice) this.feedback.textContent = 'TYPE THE WORD EXACTLY AS SHOWN'; if (retrieval) this.feedback.textContent = 'RETRIEVAL ATTEMPTS: ' + challenge.retrievalAttempts; if (!learning) this.input.focus(); }
  beginPractice() { const challenge = this.challenges.get(this.activePlayerId); if (!challenge || challenge.phase !== 'learn') return; challenge.phase = 'practice'; this.input.value = ''; this.feedback.textContent = ''; this.render(challenge); }
  checkPractice() { const challenge = this.challenges.get(this.activePlayerId); if (!challenge || challenge.phase !== 'practice') return; this.testButton.disabled = this.input.value.trim().toLowerCase() !== challenge.word.toLowerCase(); }
  beginRetrieval() { const challenge = this.challenges.get(this.activePlayerId); if (!challenge || challenge.phase !== 'practice' || this.testButton.disabled) return; challenge.phase = 'retrieval'; this.input.value = ''; this.feedback.textContent = ''; this.render(challenge); }
  submitRetrieval() { const challenge = this.challenges.get(this.activePlayerId); if (!challenge || challenge.phase !== 'retrieval') return; challenge.retrievalAttempts += 1; const result = submitSpellingAttempt({ playerId: challenge.playerId, word: challenge.word, attempt: this.input.value }); if (!result.correct) { challenge.phase = 'learn'; this.feedback.textContent = 'NOT QUITE. BACK TO PRACTICE.'; this.input.value = ''; this.render(challenge); return; } challenge.phase = 'complete'; challenge.completedAt = Date.now(); challenge.completedPhaseAt = performance.now(); this.feedback.textContent = 'CORRECT! WORMHOLE ESCAPE SUCCESSFUL'; this.input.disabled = true; this.render(challenge); }
  update(now) { if (!this.activePlayerId) { this.showNext(); return; } const challenge = this.challenges.get(this.activePlayerId); if (!challenge) return; if (challenge.phase === 'complete' && now - challenge.completedPhaseAt >= 850) { completeSpellingChallenge({ studentId: null, wordId: challenge.wordId, retrievalAttempts: challenge.retrievalAttempts, correct: true, destructionReason: challenge.reason }); this.challenges.delete(challenge.playerId); const playerId = challenge.playerId; this.activePlayerId = null; this.overlay.classList.remove('visible'); this.overlay.setAttribute('aria-hidden', 'true'); this.onComplete(playerId); this.showNext(); } }
}
